application: hogehoge-backup-test
version: 1
runtime: go
api_version: go1.6

handlers:
- url: /.*
  script: _go_app
  login: admin

env_variables:
  TARGET_BUCKET_NAME: "hogehoge-backup-bucket"
  BACKUP_PREFIX: "backup-prefix"
#  IGNORE_KINDS: "b,c" # backupから除外したいkind名をカンマ区切りで
